services:
  - type: worker
    name: wakeup-bot
    runtime: python
    pythonVersion: "3.12.0"
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: WAKEUP_BOT_TOKEN
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: CODESPACE_NAME
        sync: false
      - key: ALLOWED_CHAT_ID
        sync: false
