services:
  - type: web
    name: wakeup-bot
    runtime: python
    rootDir: wakeup-bot
    pythonVersion: "3.12.0"
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: WAKEUP_BOT_TOKEN
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: CODESPACE_NAME
        sync: false
      - key: ALLOWED_CHAT_ID
        sync: false
